# Welcome to Jekyll!

# Website settings
title: "Karthik Balasubramanian"
description: "Karthik's blog"
keywords: "Karthik B, Karthik CMU MISM, Karthik Balasubramanian, Karthik Adobe"
baseurl: "/"
#url: "http://karthikBalasubramanian.github.io"
url: "http://127.0.0.1:4000"

# author
author:
  name: 'Karthik'
  first_name: 'Karthik'
  last_name: 'Balasubramanian'
  email: 'karthikb@andrew.cmu.edu'
  linkedin_username: 'bks4line'
  github_username: 'karthikBalasubramanian'
  avatar: 'static/img/landing/profile_pic_karthik.jpg'
  desc: 'I am a Data enthusiast. My passion is to identify the actionable information from noisy data that can bolster the business needs. My fascination is always about the beautiful human mind and learning about it will be my life-time project. I run in my free time. Follow me on Strava!'
  pgp: 'PGP fingerprint <b>C3F4 A8A7 620A 9056 915B FDE0 C649 D585 83A6 936A</b>'

# localization
languages:
  # - locale: 'zh'
  #   flag: 'static/img/flags/China.png'
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://karthikBalasubramanian.github.io/static/img/blog'

# donate
# donate:
#   wechat1: 'static/img/pay/w1.jpeg'
#   wechat5: 'static/img/pay/w5.jpeg'

# comment
# changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
   name: https-karthikbalasubramanian-github-io
   public_key: N3n8ymxO3tzmAfetCxCQ6HTocyF7PMrvp1pzgkaRTNQkNKRxHnAUwxEixA86xNQv

# # share
# bshare:
#   uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
# ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
# ga:
#   id: UA-73784599-1

# growingIO
# gio:
#   id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
